; Global settings for redshift
; for more options see: https://raw.githubusercontent.com/jonls/redshift/master/redshift.conf.sample
[redshift]
; Set the day and night screen temperatures
temp-day=6500
temp-night=4400


; Set the screen brightness. Default is 1.0.
; brightness=0.9
; It is also possible to use different settings for day and night
; since version 1.8.
brightness-day=1.0
brightness-night=0.80


gamma-night=0.80

; set location manually
location-provider=manual

; Configuration of the location-provider:
; type 'redshift -l PROVIDER:help' to see the settings.
; ex: 'redshift -l manual:help'
; Keep in mind that longitudes west of Greenwich (e.g. the Americas)
; are negative numbers.
[manual]
lat=0.0
lon=1.0
